In [3]:
import numpy as np

 1. Create a 3x3x3 array with random values

In [4]:
x = np.random.random((3,3,3))
print('3x3x3 Array:\n')
print(x)

3x3x3 Array:

[[[0.3305046  0.02878003 0.48898516]
  [0.84647632 0.90074625 0.46144762]
  [0.91795274 0.22500729 0.97818999]]

 [[0.24169106 0.33651116 0.36205574]
  [0.10251786 0.80538827 0.33703934]
  [0.50438123 0.40891992 0.91713611]]

 [[0.67645321 0.43107565 0.99951133]
  [0.9202667  0.35683175 0.18986864]
  [0.87095232 0.47279614 0.3711111 ]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [5]:

matrix = np.zeros((5,5))
matrix = np.diag(1+np.arange(4),k = -1)
print('Matrix with 1,2,3,4 just below Diagonal:\n\n', matrix)

Matrix with 1,2,3,4 just below Diagonal:

 [[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [6]:
x = np.zeros((8,8), dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print('Check Borad Pattern:\n')
print(x)

Check Borad Pattern:

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [7]:
x= np.random.randn(5,5)
print("Original Array:\n")
print(x)

xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)

print("\nAfter normalization:\n")
print(x)

Original Array:

[[-0.68377848  2.24271961  0.55336895  2.0024371  -1.14829854]
 [ 0.39093749 -0.27012772 -0.0409178   1.46139788  0.32165983]
 [ 0.75082471  0.62477304 -0.48076031 -0.84197057 -1.22593017]
 [-0.47284381 -0.05180871  0.02383359 -0.36896251 -0.26442411]
 [-1.91362232  1.1516695   0.5169569  -0.79984008 -0.48904475]]

After normalization:

[[0.29589573 1.         0.59354868 0.94218894 0.18413398]
 [0.55446829 0.39541852 0.45056556 0.81201697 0.53780035]
 [0.64105578 0.61072823 0.34474113 0.25783532 0.1654561 ]
 [0.34664581 0.44794524 0.46614449 0.37163925 0.39679079]
 [0.         0.73749751 0.58478808 0.26797175 0.34274792]]


# 5.  How to find common values between two arrays?

In [8]:
array1 = np.array([0, 10, 20, 40, 60])
array2 = [10, 30, 40]
print("Array1: ", array1)
print("Array2: ", array2)
print("Common values between two arrays:", np.intersect1d(array1, array2))

Array1:  [ 0 10 20 40 60]
Array2:  [10, 30, 40]
Common values between two arrays: [10 40]


# 6.How to get the dates of yesterday, today and tomorrow?

In [9]:
import datetime as dt

today = dt.date.today()
yesterday = today - dt.timedelta(days = 1)
tomorrow = today + dt.timedelta(days = 1) 

print('Yesterday: ',yesterday)
print('Today: ', today)
print('Tomorrow: ', tomorrow)

Yesterday:  2020-07-26
Today:  2020-07-27
Tomorrow:  2020-07-28


# 7. Consider two random array A and B, check if they are equal

In [10]:
a = np.array([[1,23,5],[6,9,40]])
b =  np.array([[1,23,5],[6,9,40]])
print('Array1:\n', a)
print('Array2:\n', b)
print('\nResult is True if the Arrays are Equal \nResult is False if the Arrays are Not Equal ')
np.array_equal(a,b)

Array1:
 [[ 1 23  5]
 [ 6  9 40]]
Array2:
 [[ 1 23  5]
 [ 6  9 40]]

Result is True if the Arrays are Equal 
Result is False if the Arrays are Not Equal 


True

# 8.Create random vector of size 10 and replace the maximum value by 0 

In [11]:
vector = np.array([1,45,867,90,48,94,100,166,867,110])
print('Vector: ', vector)
print('Length of Vector: ', len(vector))

vector_max = vector.max() 
print('Maximum value:', vector_max)
index= np.where(vector == vector_max)
vector[index] = 0

print('Replacing {} by 0: {}'.format(vector_max, vector))

Vector:  [  1  45 867  90  48  94 100 166 867 110]
Length of Vector:  10
Maximum value: 867
Replacing 867 by 0: [  1  45   0  90  48  94 100 166   0 110]


# 9. How to print all the values of an array?

In [12]:
# 1-D Array :
print('For 1-D Array:')
x = np.array([12, 34, 67, 89])
for i in range(len(x)):
    print(f"The element at index {i} is: {x[i]}")

# 2-D Array: 
print('\nFor 2-D Array:')
y = np.array([[13,57,45],[34,76,88],[92,21,19],[98,67,0]])
for i in range(len(y)):
    print(f"The element at index {i} is: {y[i]}")

For 1-D Array:
The element at index 0 is: 12
The element at index 1 is: 34
The element at index 2 is: 67
The element at index 3 is: 89

For 2-D Array:
The element at index 0 is: [13 57 45]
The element at index 1 is: [34 76 88]
The element at index 2 is: [92 21 19]
The element at index 3 is: [98 67  0]


# 10.Subtract the mean of each row of a matrix

In [13]:

arr = np.array([[1, 100, 0, 0], [2, 110, 0, 0], [3, 120, 0, 0]])
print('Initial Array:\n', arr)
print('Mean of Each row: ',arr.mean(axis=1))
mean = arr - arr.mean(axis=1, keepdims=True) 
print('\nResultant Matrix After Subtracting Mean:\n',mean)

Initial Array:
 [[  1 100   0   0]
 [  2 110   0   0]
 [  3 120   0   0]]
Mean of Each row:  [25.25 28.   30.75]

Resultant Matrix After Subtracting Mean:
 [[-24.25  74.75 -25.25 -25.25]
 [-26.    82.   -28.   -28.  ]
 [-27.75  89.25 -30.75 -30.75]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [14]:
Z = np.ones(10)
print("Initial Vector:\n",Z)
I = np.random.randint(0, len(Z),20)
print("Random Values:\n",I)
Z += np.bincount(I, minlength=len(Z))
print("Resultant Vector:\n",Z)

Initial Vector:
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Random Values:
 [8 8 6 6 6 9 3 1 3 8 2 2 8 5 4 7 0 3 5 4]
Resultant Vector:
 [2. 2. 3. 4. 3. 3. 4. 2. 5. 2.]


# 12.How to get the diagonal of a dot product?

In [15]:
A = np.random.randint(0,10,(3,3))
B= np.random.randint(0,10,(3,3))

print("Array A:\n", A)
print("Array B:\n", B)

print('\nDot product:\n',np.dot(A,B))
dot = np.diag(np.dot(A, B))
print('\nThe Diagonal Elements are:\n', dot)

Array A:
 [[8 3 6]
 [5 0 1]
 [2 6 8]]
Array B:
 [[3 5 5]
 [4 2 5]
 [1 1 4]]

Dot product:
 [[42 52 79]
 [16 26 29]
 [38 30 72]]

The Diagonal Elements are:
 [42 26 72]


# 13.How to find the most frequent value in an array?

In [16]:

Z = np.random.randint(0,10,30)
print ("Array:", Z)
print('Most Frequent Value:', np.bincount(Z).argmax())

Array: [8 9 7 2 9 6 8 2 9 7 3 8 3 3 2 8 4 8 2 2 6 4 7 8 7 1 2 0 5 0]
Most Frequent Value: 2


# 14.How to get the n largest values of an array

In [17]:
Z = np.arange(100)
np.random.shuffle(Z)
n = int(input('Enter the value of n: '))
print(f"{n} Largest values in array: ", Z[np.argsort(Z)[-n:]])

Enter the value of n: 5
5 Largest values in array:  [95 96 97 98 99]


# 15.How to create a record array from a regular array?

In [18]:
print('For a Single Array:\n')
x3 = np.array([['Riya',98, 99],['Ankita', 90, 92],['Divyam', 89, 90]])

print('Regular Array:\n', x3)
rec = np.core.records.fromarrays(x3.T,names='name,mks1,mks2',formats='S80, i8, i8') # The arrays are now transposed'

print('\nRecord Array:', rec)
print('Type of Result:', type(rec))

For a Single Array:

Regular Array:
 [['Riya' '98' '99']
 ['Ankita' '90' '92']
 ['Divyam' '89' '90']]

Record Array: [(b'Riya', 98, 99) (b'Ankita', 90, 92) (b'Divyam', 89, 90)]
Type of Result: <class 'numpy.recarray'>
